### ISSUE TITLE
OAuth2macOS target does not build with Xcode 10.2

### ISSUE THREAD

**Issue by GeorgeSealy** [p2/OAuth2#311]
We are in the process of moving from Xcode 10.1 -> Xcode 10.2. This is to allow us to work with Swift 5 in our own code base.

When compiling OAuth2 in Xcode 10.2, the compiler fails with:

`OAuth2/SwiftKeychain/Keychain/Keychain.swift:49:44: error: 'archivedData(withRootObject:)' is only available on OS X application extension 10.11 or newer`

The same code builds under Xcode 10.1. Switching the minimum deployment target to macOS 10.11 fixes the problem, but may not be the desired solution.

Also of note is that the OAuth2Tests target still has a Swift language version of 3.0, not 4 (like the other targets).
